### ISSUE TITLE
Stopped working returning "Sends a OPTIONS request" error

### ISSUE THREAD

**Issue by rjcoelho** [SumoLogic/livetail-cli#17]
```
### Authenticating ###
Traceback (most recent call last):
  File "<string>", line 184, in <module>
  File "<string>", line 95, in login
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 480, in get
    """Sends a OPTIONS request. Returns :class:'Response' object.
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request

  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r.elapsed = datetime.utcnow() - start
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(54, 'Connection reset by peer')",)
livetail returned -1
```

Using latest binary (v1.0 from 2 Feb 2016).

**Comment by cddude229** [comment]
Hi @rjcoelho, can you try again now?  We had just rolled out a stricter set of TLS rules and, unfortunately, this was an unintended side-effect.  We have rolled back the change and everything should work as expected.  We're very sorry for the inconvenience!

**Comment by rjcoelho** [comment]
@cddude229 its working again! i will close this issue. thanks!

**Comment by cddude229** [comment]
Fantastic.  Sorry again for the inconvenience!
