### ISSUE TITLE
KeyError: 'deployment' running livetail

### ISSUE THREAD

**Issue by kinghuang** [SumoLogic/livetail-cli#26]
I just downloaded livetail for macOS. No matter what I do with it, it errors out with a KeyError.

```
$ ./livetail "_collector=psc-dev-gen_th6z8bnkixytyjxckons9mhr6" 
Traceback (most recent call last):
  File "livetail.py", line 139, in <module>
KeyError: 'deployment'
[13047] Failed to execute script livetail
```

**Comment by mmaetzler** [comment]
Same issue here:

```
./livetail "_source=ABC"                                                                                              
Traceback (most recent call last):
  File "livetail.py", line 139, in <module>
KeyError: 'deployment'
[80273] Failed to execute script livetail
```

Version:
```
./livetail -v 
Sumo Logic Live Tail CLI Version (2.0)
```

**Comment by mmaetzler** [comment]
After going through some of the open issues I found the mistake for my error. I was running `./livetail` in a folder that already had a `config.json` file created by some other tool in the past. As indicated in this [issue](https://github.com/SumoLogic/livetail-cli/issues/13), `livetail` tries to create the config file right next to where the binary sits (instead of e.g. some user specific folder). After I've moved `livetail` somewhere else, I was able to use it.

I'd recommend to update `livetail` to store the config file somewhere else and with the right permissions (not 644).
